### PR TITLE
Adding support for Django RestFramework

### PR DESCRIPTION
**Pull request by enzofrnt**
Related to: #140

Hi, I've just upgraded the plugin to fully support the Django Rest Framework.

Modifications include:

- The old code has been retained, with minor upgrades.
  - Adding to `django_eventstream.utils` a `get_cors_from_settings` method
- Rearranged the static folder organization.
- Added a viewset for Server-Sent Events (SSE) that is capable of redirecting to the correct renderer with the appropriate response.
- Introduced a renderer for SSE streams. This renderer is equipped to handle SSE streams with the correct response headers and the right content type.
- Implemented a renderer for the SSE browsable API:
  - Added `browsable-api-eventstream.html`, a template file that is an edited version of the `base.html` file from the Django Rest Framework.
  - Added `browsable-api-eventstream.js`, a JavaScript script that provides all the necessary functionality for the `browsable-api-eventstream.html` template to correctly display the SSE stream, using `reconnecting-eventsource.js`.
  - Added `browsable-api-eventstream.css` to supply the CSS for the `browsable-api-eventstream.html` template.
- Updated DOCs
- Adding possibility to install with or without Django Rest Framework. Check `__init__.py` files.
- Adding a fully functional example `chat-restframework`

The Browsable API is fully usable, as shown here:

Preview Image

image

The system will automatically return an SSE Stream when called by a request header that contains `Accept: text/event-stream`.

### CODE REVIEW

**Comment by jkarneges** [comment]
Thank you. Will look at this soon.

**Comment by enzofrnt** [comment]
Nice thanks you !

**Comment by enzofrnt** [comment]
So ? 😋😅

**Comment by jkarneges** [comment]
Ok, finally looked at this!

There is a lot here. I'd like to split this up:

1. Please move the new static assets into the chat-restframework example, to minimize the library's surface area. We could maybe graduate these files into the library later but would need to think about it.
2. Don't change the path of existing assets, at least not yet, since this could break apps and will require a major version bump.
3. Be sure any needed CORS stuff will work with django-cors-headers too, since I plan to deprecate our built-in CORS logic in favor of everyone using django-cors-headers.

Also, a question: what is the purpose of messages_types?

**Comment by enzofrnt** [comment]
Hi @jkarneges, 

1. I can't delete those assets from the module. Without those assets, the browsableAPI that I made will not work. But what do you mean by asset ? Every HTML, JS and CSS files ?
image

2. I will change that.

3. I will verify and push every modification with info in commit

**Comment by enzofrnt** [comment]
Path fix.
Looking for CORS tomorow in france.

**Comment by enzofrnt** [comment]
Message type is use do define what type of event you want to send. That could be helpful in some case.

**Comment by enzofrnt** [comment]
Everything for CORS look's fine

**Comment by Sonictherocketman** [comment]
Would love to see this btw. Any update on the status?

**Comment by enzofrnt** [comment]
Hi, @jkarneges any news about this ?
thx.

**Comment by jkarneges** [comment]
> Message type is use do define what type of event you want to send. That could be helpful in some case.

Can you explain this further? It doesn't look like the field is used anywhere.

**Comment by jkarneges** [comment]
> The goal of the merge-request is to add full support for Django-restframework deleting those files will delete the support for browsableAPI that a part of Django-restframework.

Ah, I am not familiar enough with DRF features. So DRF allows browsing endpoints out of the box? Is this kind of thing always on or something the developer opts-in to maybe in debug mode?

**Comment by enzofrnt** [comment]
Hi @jkarneges,

that something enable by default in Django RestFramework mode. 

image

Usually it's disable in production.

**Comment by jkarneges** [comment]
Let's put the css file under a `css/` path. I'd even be okay with the new js file going under `js/` as well, as long as the old js files aren't moved. Be sure the html file is updated to fetch from the right paths.

> Usually it's disable in production.

How can it be disabled?

**Comment by enzofrnt** [comment]
@jkarneges 
Done :)

> How can it be disabled?

Probably with something like that :
https://testdriven.io/tips/9aee5b07-bf7a-475b-91cc-d46e8f5c512a/

Django REST is using renderersin this example to disable the browsableAPI we setthe defaultrenderer on json so no more api renderer that made the browsableAPI, it may need some tricks to work with sse here by adding the new renderer that i made

**Comment by jkarneges** [comment]
The references to the existing js files need to be corrected in the html template.

> > Message type is use do define what type of event you want to send. That could be helpful in some case.

> Can you explain this further? It doesn't look like the field is used anywhere.

I guess the field is used by the browsable view?

It would be good to have a way to disable the browsable view before merging.

**Comment by enzofrnt** [comment]
Hi, please do not accept the merge request now, i'm improving some things about the browsable view… and to be able to disable it as we can with original browsable view.
Also, @jkarneges can i take a look at the conflict to resolve them ?
thx.

**Comment by enzofrnt** [comment]
I did not add comment or docstring because the rest of the code didn't have comment.
Maybe create an issue related to this upgrade ?

**Comment by enzofrnt** [comment]
It is now possible to disable the browsable view. The message type is related to SSE in general. SSE uses message types to communicate specific events, such as the "keep-alive" message that is used to keep the stream active, and the "error" message to indicate an error. This allows us to send other types of messages if needed, to handle specific scenarios in our application.

**Comment by enzofrnt** [comment]
Hi, @jkarneges any news ?

**Comment by enzofrnt** [comment]
🙏🏻

**Comment by jkarneges** [comment]
Hi @enzofrnt, the branch is still showing a conflict.

**Comment by enzofrnt** [comment]
Hi, @jkarneges every thing is fix.
Thank you.

**Comment by jkarneges** [comment]
Getting this error when running the example:
```
  File "/Users/jkarneges/src/fanout/django-eventstream/examples/chat-restframework/../../django_eventstream/views/sseview.py", line 87, in _stream_or_respond
    data = {'channels': ', '.join(channels) or "", 'messages_types': ', '.join(self.messages_types) or "message"}
                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: can only join an iterable
```

**Comment by enzofrnt** [comment]
HI, @jkarneges just fixed it !
Finally :)

**Comment by jkarneges** [comment]
Almost there.

I tried disabling the browser view by removing the renderer like this:

```
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        #'rest_framework.renderers.BrowsableAPIRenderer',
        'django_eventstream.renderers.SSEEventRenderer',
        #'django_eventstream.renderers.BrowsableAPIEventStreamRenderer'
    ] 
}
```

But this causes a strange response to be served:

Screenshot 2024-05-22 at 5 26 46 PM

**Comment by enzofrnt** [comment]
Maybe because the room don't exist..
But not sure i will take a look at this.

**Comment by enzofrnt** [comment]
Now, every thing may work as needed.

**Comment by enzofrnt** [comment]
As junior/student dev, I made a lot of mistake. Sorry.

**Comment by enzofrnt** [comment]
Hi, any news ? : )

**Comment by jkarneges** [comment]
I may clean some things up before the next release but this looks good! Thank you :)

**Comment by enzofrnt** [comment]
Thanks you !

**Pull request merged**
