### PR TITLE
Fix dependencies issue

### PR DESCRIPTION
**Pull request by enzofrnt**
Related to #153, that should be sufficient.
We really need better tests and CI for these kinds of things.
I would like to be a maintainer.

### CODE REVIEW

**Comment by jkarneges** [comment]
> I would like to be a maintainer.

Let me look into this, may need company approval.

**Comment by enzofrnt** [comment]
> > I would like to be a maintainer.
> 
> 
> 
> Let me look into this, may need company approval.

Thanks.
You can send me email on enzo@enzo-frnt.fr

**Comment by enzofrnt** [comment]
@jkarneges I post here because that here we talk last time, any news about my proposition ?
Thanks.

**Comment by jkarneges** [comment]
Thanks for the ping. I've sent you a mail. We can continue the discussion there.

**Pull request merged**
