### PR TITLE
Faster event log trimming

### LINKED ISSUE #93: trim_event_log inefficient
Is there a reason to not use a single delete statement when [trimming the event log](https://github.com/fanout/django-eventstream/blob/d09bcd95c1476463803b1265be606f4eae40c6fa/django_eventstream/storage.py#L114)?
The code creates a query for every single event that needs to be deleted.
I can create a PR if that's unintentional.

### PR DESCRIPTION
**Pull request by Schlepptop**
Fixes #93

### CODE REVIEW

**Comment by jkarneges** [comment]
Thanks! I think we still want the loop, since the query is limited to the batch size.

**Comment by Schlepptop** [comment]
Good catch on the loop, I can add that again. But do we even want to limit it? Deletion really isn't that expensive of an operation, why do we need to restrict the batch size? 
Because querysets are lazy, it is evaluated only upon slicing so that's how we limit the clause if we do want to.

**Comment by jkarneges** [comment]
The batch limit is there so that all the results don't get buffered in memory. I seem to recall that even though querysets are evaluated lazily, iterating a queryset may still cause all the items in the entire set to end up in memory.

If calling `delete()` within a queryset doesn't cause all the items in the set to first be read into memory, and also if the deleting isn't atomic (i.e. doesn't block access to the table in between deletions of each item in the queryset), then the batching may be unnecessary.

**Comment by Schlepptop** [comment]
Ok then I'll just remove it all together.
.delete() won't load any of the deleted object into memory. Also all items are deleted at once (it's one sql `DELETE ... WHERE ...` statement after all), so the database is only blocked during that one query.

**Comment by enzofrnt** [comment]
Should we close this @jkarneges ?

**Comment by jkarneges** [comment]
Yeah I suppose so. Can always reopen if it turns out there's a good way to do this.

**Pull request closed without merging**
