### PR TITLE
Use Redis as storage

### PR DESCRIPTION
**Pull request by erfantarighi**
I added a RedisStorage class which is faster and more efficient, I strongly recommend using RedisStorage as the default storage.
because in high traffic using the Django default database can harm or make the backend slow (MySQL has a connection limit)

### CODE REVIEW

**Comment by jkarneges** [comment]
Conceptually looks good.

Comments:

* It looks like event_counter is double-incremented when appending an event.
* Ideally, appending should be transactional. Might need some `watch` statements. Or could do it as a lua script.
* Consider pipelining reads, otherwise there would be a round trip per event.
* I wonder about configuring using a URL and initializing with `Redis.from_url()`, instead of configuring using a dict (or maybe allow both).
* I guess there's no need for an explicit trim method since redis will auto expire via TTLs?

**Comment by erfantarighi** [comment]
Thanks for the comments @jkarneges 

- Yes, it's my bad, I will fix it
-  There are no transactional actions in Redis, Redis is a single-thread software which means you won't face concurrency issues
- I used pipelines on the append function
- Yes, we can use the from_url function but it's not that safe for input, developers may be confused about setting the URLs especially if they have some characters such as # in their passwords, in this case, they should encode (Using URLEncode) their URLs and then set them.
- Yes, I removed it because I used Redis TTLs

**Comment by jkarneges** [comment]
Well, there are transactions of sorts using multi/exec. I forgot that the python lib does this by default when pipeline mode is used.

I'll merge this but I strongly suggested pipelining the reads too. Otherwise, a single call to `get_events()` may do many round trips (e.g. fetching 100 items is 100 round trips).

**Comment by williamrexhardin** [comment]
This change is particularly interesting. Will there be a release available soon with these changes? 5.1.1?

**Comment by jkarneges** [comment]
Released 5.2.0 with this change.

**Pull request merged**
